Revert "remove coverage temporarily"
This reverts commit abe0bc9c7c74428f553b6360633f5ed46ed4399a.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -40,3 +40,37 @@ jobs:
       # Run tests
       - name: Run tests
         run: dotnet test $SLN_PATH --configuration Release --no-build --verbosity normal  --collect:"XPlat Code Coverage"  --results-directory ./$COVERLET_PATH
+
+      # Remove 'empty' coverage files - they cause the CodeCoverageSummary action to fail
+      - name: Remove empty coverage files
+        run: find ./$COVERLET_PATH -type f -exec sh -c 'for f in "$@"; do grep -l "<sources />" "$f" && rm -f -- "$f"; done' _ {} + || true
+
+      # check files
+      - name: Check files
+        run: find ./$COVERLET_PATH -type f
+
+      # check glob
+      - name: Check glob
+        run: shopt -s globstar; printf %s\\n ./$COVERLET_PATH/**/coverage.cobertura.xml
+
+      # Code Coverage Report
+      - name: Code Coverage Report
+        uses: irongut/CodeCoverageSummary@v1.3.0
+        with:
+          filename: $COVERLET_PATH/**/coverage.cobertura.xml
+          badge: true
+          fail_below_min: true
+          format: markdown
+          hide_branch_rate: false
+          hide_complexity: true
+          indicators: true
+          output: both
+          thresholds: '60 80'
+
+      # Add Coverage PR Comment
+      - name: Add Coverage PR Comment
+        uses: marocchino/sticky-pull-request-comment@v2
+        if: github.event_name == 'pull_request'
+        with:
+          recreate: true
+          path: code-coverage-results.md
